name: sounds
version: 1.0.0-beta13
homepage: https://github.com/bsutton/sounds
documentation: https://github.com/bsutton/sounds/wiki
description: Sounds provide a complete api and Widgets for audio playback and recording. Both iOS and Android are supported.
repository: https://github.com/bsutton/sounds
environment: 
  sdk: '>=2.1.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'
dependencies: 
  device_info: '>=0.4.2+4 <2.0.0'
  flutter_spinkit: ^4.0.0
  meta: ^1.1.8
  path: ^1.6.4
  path_provider: ^1.6.7
  provider: ^4.1.0
  sounds_common: #^1.0.0
    path: ../sounds_common
  sounds_platform_interface:
    path: ../sounds_platform_interface

  uuid: ^2.0.4
  flutter: 
    sdk: flutter
dev_dependencies: 
  dart_numerics: ^0.0.5
  pedantic: ^1.9.0
  effective_dart: ^1.2.1
  dcli: ^0.33.0
  e2e: ^0.7.0
  lint: ^1.1.1
  pub_semver: ^1.4.4
  pigeon: 
    path: ../../packages/packages/pigeon

  flutter_test: 
    sdk: flutter
  flutter_driver: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: com.bsutton.sounds
        pluginClass: Sounds
      ios: 
        pluginClass: Sounds


