name: sounds_common
version: 1.0.8
homepage: https://github.com/bsutton/sounds_common
documentation: https://github.com/bsutton/sounds_common/wiki
description: A shared library for the sounds and sounds_codec packages. Provides MediaFormat, Track and small set of utility functions.
repository: https://github.com/bsutton/sounds_common
environment: 
  sdk: '>=2.8.1 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'
dependencies: 
  intl: ^0.16.1
  logger: '>=0.7.0+2 <1.0.0'
  meta: ^1.1.8
  path: ^1.6.4
  pedantic: ^1.9.0
  uuid: ^2.0.4
  flutter: 
    sdk: flutter
dev_dependencies: 
  effective_dart: ^1.2.1
  test: ^1.14.4
